
services:
  db:
    image: mysql:8
    container_name: mysql
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: pnm-todo
    ports:
      - "3306:3306"
    volumes:
      - mysql-data:/var/lib/mysql
    networks:
      - backend

  app:
    image: shagya30/pnm-todo-be:latest
    container_name: pnm-todo-be
    environment:
      TZ: Asia/Jakarta
    volumes:
      - ./.env:/app/.env
    depends_on:
      - db
    networks:
      - backend
    restart: always
    env_file:
      - .env
    ports:
      - "3000:3000"

volumes:
  mysql-data:

networks:
  backend:
    driver: bridge
