
services:
  db:
    image: mysql:8.4.5
    container_name: pnm-todo-db
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: pnm-todo
    volumes:
      - ./mysql/init.sql:/docker-entrypoint-initdb.d/init.sql
    network_mode: host
    restart: always
    ports:
      - "3306:3306"
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost", "-u", "root", "-p$DB_PASSWORD"]
      interval: 30s
      retries: 5
      start_period: 10s
      timeout: 10s

  app:
    image: shagya30/pnm-todo-be:latest
    container_name: pnm-todo-be
    environment:
      TZ: Asia/Jakarta
      DB_HOST: localhost
    volumes:
      - ./.env:/app/.env
    depends_on:
      db:
        condition: service_healthy
    network_mode: host
    restart: always
    env_file:
      - .env
    ports:
      - "3000:3000"

volumes:
  mysql-data:

networks:
  default:
