version: '3.8'

services:
  app:
    image: shagya39/pnm-todo-be:latest
    container_name: pnm-todo-be
    environment:
      TZ: Asia/Jakarta
    volumes:
      - ./.env:/app/.env
    network_mode: host
    restart: always
